### ISSUE TITLE
Images error

### ISSUE THREAD

**Issue by hassanrehman01398** [TSTsankov/ANN_FKD#1]
Its not working on images other than train images and plus what accuracy you are getting?

**Comment by TSTsankov** [comment]
@hassanrehman01398 - this was not a very successful project, I'd recommend you to start from scratch, with what you are trying to achieve, and not use anything from this repository.

Here is the link to the original data set: [https://cmu-perceptual-computing-lab.github.io/foot_keypoint_dataset/](https://cmu-perceptual-computing-lab.github.io/foot_keypoint_dataset/)

**Comment by hassanrehman01398** [comment]
I am trying to train a model for foot and I am not getting close to it.Can
you help me.I searched whole internet but I didn't get any solution.I want
to train it for my app.Thanks

**Comment by TSTsankov** [comment]
You need to come up with the solution yourself, I doubt you will find one on the internet at the moment. You can start with the previously mentioned data set, tough it might not be good enough for something like real time tracking. Play around with the different ML approaches, identify the one most suitable for the task, then play around with it to achieve better detection results.

**Comment by hassanrehman01398** [comment]
Yeah I am playing with different kits but I am not getting a slit bit
closer in real time tracking :(
